sudo: required
dist: trusty
branches:
  only:
  - master
language: cpp
compiler:
- gcc
- clang
env:
- CC=i586-mingw32msvc-gcc OPTIONS="-DBUILD_CLAR=OFF -DWIN32=ON -DMINGW=ON"
before_install:
- sudo apt-get update -qq -y
- sudo apt-get install -qq -y g++-multilib mingw32
# - sudo add-apt-repository ppa.launchpad.net/tobydox/mingw-x-precise -y
# - sudo apt-get update -q
# - sudo apt-get install mingw-x-gcc -y
# - sudo apt-get install mingw-x-binutils -y
# - sudo apt-get install mingw-x-runtime -y
before_script:
- if [ -n "${GH_TOKEN}" ] && [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}"
  == "false" ]; then pip install pygithub; pip install pygithub3; fi
- cd build
- cmake ..
- cd ..
install:
- if [ "$CXX" == "clang++" ]; then export CXXFLAGS="-std=c++11"; fi
script:
- if [ -n "${GH_TOKEN}" ] && [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}"
  == "false" ]; then python3 tools/deploy.py; fi
- python3 tools/sqf_wrapper_validation.py
- cd build
- make
- $CXX --version
# notifications:
#   email:
#     on_success: never
#     on_failure: change
#   slack:
#     rooms:
#      - secure: 1lei46T8NR4kfB2H5mEwyZya2o3mj1K9fBWAVAww1laYs+Vwn/S8IGukxkhvCLboWgEn+tnqAyFVS13K0VSwSOHfBERadCxai2gsgz0aGlFANtxLnbMc4SBS8gXwEBfce2GN3mj4dIEi3oU/3fcvIY0mYGyM9MeEAMJMTouU3eV/J7ry5XZ1sNFnnfZkyMOYqsVa/Vz+qQzzqRNRBCiNL4N+n/gEJEqLOc54s3v4A5x+lcJK2Upv0U2mHfqjb4UrqrT55TLiKEDVC5WsHRZoowTb5QLGHvOJ2Y0tpUxFIOKoEC/qKHTpbojyUL6rdx1W6ac/yRuyBKR4Jw31hfts2JCesWUbSfls4vLzJOe/3wtt8fQMjQNlkEgnv1vYCEAzDUseRd+8zc+EohRO5K31JHosLSnyzG/pajUoXtrAiJwFds33ZiBHOJwzciMTJpRbtg898gNg0640c1ZqZHH0PIBBFPz+MRhHOoLEDVrK2S7aukVW4EtnDAenbkv83813djwWbm3zqzxXEMNttjaoI4XYUCraoEH4TsGaVN9Sm1k8Uta36wVsS/AAqQR+vdLDPTfLk5Cbdnrc/U1g47I72xGlaBnL4tONTq+XpvEot0EPs92TTk719LYG64nQ0D1auZpO8Tormk5mGS2aNtGp3GLgA9sXVTdFn9n4s17PIew=
#     on_success: change
env:
  global:
    secure: agYEwpL95+e0vVIJ6H/UXJwiY0ubCFoNM7SoGFikr+ZV609OeL7KPS7gG7TV57HUP7lPv05JIntFAn37NZjKptZYJTBnmTPT7mmS/fn3LfuFwldvD2m+PUclz5cO2WMM+utWi+JnvpYPficdlLoHOlW9NjigsgFT/Xd49MkDyxpxCZ2C3KiSzOy4EAV+UNMDiq5+iUKNNMfTINYz2ZTF4muBQb4oGzpriS/4sEUKt1mOjZNGf2tX+JpppjDCnic9Wo3BTixIhgB/Ja0LvYuAoaERSFPioxj50J4oQemyfuGdabCM3D2Xo0i4OpNsM+Au9iXQaL9bQRvTfVSSN1T6KARmuw134MjuPq9G4ppRIEHeKzirqUpMNw+ja/No7I5111Cq0fwm/Y+ZqaxPf1YRnt5jLweggngKrb9672IkrW7M10pvleUXV5RWYBXkfwWxyNatU7dt231gS7n1jTOOvGDltvyHjnZSuCR82IevE4waCxtfGAfgwqYj14vVyQoxLIbFcFpJJ3ANRdwpHYaIlcJ03GSG5luRQ/5prwIEmweS1XlGM400XVjWpW34pHIUdjzuFyiDuSWrEWukjv57XCk7etpDTfp2rtV5tghXwqfa76SpjsIT1ooJgjL/3nrNrR3sFKWDcaC6okeB1nBZ/Fdg1GpXztf54dcyQdikqNY=
