version: "{build}"

image: Visual Studio 2017 Preview

branches:
  only:
  - master
  - develop

configuration:
- RelWithDebInfo

environment:
  matrix:
    - platform: Win32
      vcproj_dir: vcproj
      vcproj_file: vcproj\Intercept.sln
      cmake_gen: "Visual Studio 15 2017"
      cmake_args: ""

    - platform: x64
      vcproj_dir: vcproj64
      vcproj_file: vcproj64\Intercept.sln
      cmake_gen: "Visual Studio 15 2017 Win64"
      cmake_args: "-DUSE_64BIT_BUILD=ON"

matrix:
  fast_finish: true

before_build:
  - mkdir build
  - cd %vcproj_dir%
  - cmake .. -G "%cmake_gen%" %cmake_args%
  - cd ..

build:
  parallel: true
  verbosity: minimal

build_script:
  - msbuild "%vcproj_file%"
  
on_success:
  - ps: |
      Set-Location %APPVEYOR_BUILD_FOLDER%
      New-Item artifacts\intercept\client\include -type directory
      Copy-Item src\client\headers\* artifacts\intercept\client\include
      
      New-Item artifacts\intercept\client\lib -type directory
      Copy-Item build\win32\intercept_client\RelWithDebInfo\intercept_client.lib artifacts\intercept\client\lib
      
      New-Item artifacts\intercept\client\lib64 -type directory
      Copy-Item build\win64\intercept_client\RelWithDebInfo\intercept_client.lib artifacts\intercept\client\lib64
      
      New-Item artifacts\intercept\host\@intercept\addons -type directory
      Copy-Item build\win32\intercept\RelWithDebInfo\intercept.dll artifacts\intercept\host\@intercept
      Copy-Item build\win32\intercept\RelWithDebInfo\intercept.pdb artifacts\intercept\host\@intercept
      Copy-Item build\win64\intercept\RelWithDebInfo\intercept_x64.dll artifacts\intercept\host\@intercept
      Copy-Item build\win64\intercept\RelWithDebInfo\intercept_x64.pdb artifacts\intercept\host\@intercept
      
      tools\armake_x64.exe build rv\addons\core artifacts\intercept\host\@intercept\addons\intercept_core.pbo
      
      7z a "artifacts\intercept_{build}.zip" "%APPVEYOR_BUILD_FOLDER%\artifacts\intercept"
      Push-AppveyorArtifact "artifacts\intercept_{build}.zip"  
  
artifacts:
- path: build\win32\intercept_client\RelWithDebInfo\intercept_client.lib
  name: win32_client_lib
- path: build\win32\intercept\RelWithDebInfo\intercept.dll
  name: win32_host_lib
- path: build\win32\intercept\RelWithDebInfo\intercept.pdb
  name: win32_host_pdb
- path: build\win64\intercept_client\RelWithDebInfo\intercept_client.lib
  name: win64_client_lib
- path: build\win64\intercept\RelWithDebInfo\intercept_x64.dll
  name: win64_host_lib
- path: build\win64\intercept\RelWithDebInfo\intercept_x64.pdb
  name: win32_host_pdb
