version: "{build}"

branches:
  only:
  - master
  - develop

configuration:
- Debug

platform: Win32

before_build:
  - mkdir build
  - cd vcproj
  - cmake .. -G "Visual Studio 14 2015"
  - cd ..

build:
  project: vcproj\Intercept.sln
  parallel: true
  verbosity: minimal
