version: "{build}"

image: Visual Studio 2017

branches:
  only:
  - master
  - develop

only_commits:
  files:
    - src/

configuration:
- Debug

platform: Win32

before_build:
  - mkdir build
  - cd vcproj
  - cmake .. -G "Visual Studio 15 2017"
  - cd ..

build:
  project: vcproj\Intercept.sln
  parallel: true
  verbosity: minimal
